// <auto-generated />
namespace Store.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productimagechnages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productimagechnages));
        
        string IMigrationMetadata.Id
        {
            get { return "201711040943086_product-image chnages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
